### ISSUE TITLE
Resize cube example crashed

### ISSUE THREAD

**Issue by happydpc** [StarArawn/harmony#52]
Here is the failed info, when resize the skybox may need to recreate.

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Extent { width: 1280, height: 960, depth: 1 }`,
 right: `Extent { width: 1280, height: 963, depth: 1 }`: Extent state must match extent from view'

**Comment by StarArawn** [comment]
@happydpc Issue should be fixed now. Let me know if that isn't the case!

**Comment by happydpc** [comment]
Yes, it's ok now.

**Comment by StarArawn** [comment]
@happydpc Yeah that is a known issue I'm currently re-writing the skybox stuff in a separate branch, but our asset loading is a higher priority atm.

**Comment by happydpc** [comment]
Oh, I see. Hope we can achieve this result.  
![image](https://user-images.githubusercontent.com/771776/83282486-3de5d080-a20c-11ea-874c-5e06408efd1d.png)

I have tested some cube with pure color, main color is white. But comes out this. I am wondering is there anything missing? the light?  Thank you.
![image](https://user-images.githubusercontent.com/771776/83282762-a634b200-a20c-11ea-84fe-b24b5dfcfa04.png)

**Comment by happydpc** [comment]
![image](https://user-images.githubusercontent.com/771776/83282835-c1072680-a20c-11ea-85d3-a490ca40bdb0.png)
